import unittest
import pet.exceptions


class TestPetExceptions(unittest.TestCase):

    def setUp(self):
        pass

    def test_something(self):
        pass
